In [61]:
import tensorflow as tf

In [62]:
x_data = tf.Variable([[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]], shape=[5,3], dtype=tf.float32)

In [63]:
y_data = tf.Variable([[152],[185],[180],[196],[142]], shape=[5,1], dtype=tf.float32)

In [64]:
class Model(object):
    def __init__(self):
        self.W = tf.Variable(tf.random.normal(shape=[3,1]), shape=[3,1], dtype=tf.float32, name='Weight')
        self.b = tf.Variable(tf.random.normal(shape=[1])  , shape=[1], dtype=tf.float32, name='bias')
    def __call__(self, X):
        return tf.matmul(X, self.W) + self.b

In [65]:
@tf.function
def loss(expected_y, observed_y):
    return tf.reduce_mean(tf.square(expected_y - observed_y))

In [66]:
@tf.function
def train(model, inputs, outputs, learning_rate=0.01):
    with tf.GradientTape() as t:
        current_loss = loss(model(inputs), outputs)
    dW, db = t.gradient(current_loss, [model.W, model.b])
    model.W.assign_sub(learning_rate * dW)
    model.b.assign_sub(learning_rate * db)

In [67]:
model = Model()

In [68]:
Ws = []
bs = []

In [69]:
for step in range(2001):
    current_W = model.W
    current_b = model.b
    current_loss = loss(model(x_data), y_data)
    train(model, x_data, y_data, learning_rate=1e-5)
    if step%100 == 0:
        print(step, model(x_data), y_data)
    

0 tf.Tensor(
[[55.005856]
 [52.814526]
 [58.9411  ]
 [63.664406]
 [37.39497 ]], shape=(5, 1), dtype=float32) <tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]], dtype=float32)>
100 tf.Tensor(
[[159.60974]
 [178.98244]
 [183.02686]
 [198.81418]
 [133.71979]], shape=(5, 1), dtype=float32) <tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]], dtype=float32)>
200 tf.Tensor(
[[159.38208]
 [179.13878]
 [182.95743]
 [198.76138]
 [133.92714]], shape=(5, 1), dtype=float32) <tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]], dtype=float32)>
300 tf.Tensor(
[[159.1605 ]
 [179.29092]
 [182.88986]
 [198.70993]
 [134.12898]], shape=(5, 1), dtype=float32) <tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[152.],
       [185.],
       [