In [9]:
import tensorflow as tf

In [10]:
sess = tf.Session()

In [11]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])

In [12]:
matrix2 = tf.constant([[1.], [2.]])

In [13]:
print('Matrix 1 shape', matrix1.shape)

Matrix 1 shape (2, 2)


In [14]:
print('Matrix 2 shape', matrix2.shape)

Matrix 2 shape (2, 1)


In [15]:
tf.matmul(matrix1, matrix2).eval(session=sess)

array([[ 5.],
       [11.]], dtype=float32)

In [16]:
(matrix1 * matrix2).eval(session=sess)

array([[1., 2.],
       [6., 8.]], dtype=float32)

In [20]:
(matrix1 * 2).eval(session=sess)

array([[2., 4.],
       [6., 8.]], dtype=float32)

In [21]:
(matrix1 * [2]).eval(session=sess)

array([[2., 4.],
       [6., 8.]], dtype=float32)

In [22]:
(matrix1 * [2,4]).eval(session=sess)

array([[ 2.,  8.],
       [ 6., 16.]], dtype=float32)

In [24]:
(matrix1 * [[2],[4]]).eval(session=sess)

array([[ 2.,  4.],
       [12., 16.]], dtype=float32)

In [25]:
(matrix1 * [[2, 4],[3, 6]]).eval(session=sess)

array([[ 2.,  8.],
       [ 9., 24.]], dtype=float32)