In [1]:
import tensorflow as tf

In [2]:
sess = tf.Session()

In [6]:
tf.reduce_mean([1, 2], axis=0).eval(session=sess)

1

In [8]:
x = [[1., 2.], [3., 4.]]

In [9]:
tf.reduce_mean(x).eval(session=sess)

2.5

In [10]:
tf.reduce_mean(x, axis=0).eval(session=sess)

array([2., 3.], dtype=float32)

In [11]:
tf.reduce_mean(x, axis=1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

In [12]:
tf.reduce_mean(x, axis=-1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

In [13]:
tf.reduce_sum(x).eval(session=sess)

10.0

In [14]:
tf.reduce_sum(x, axis=0).eval(session=sess)

array([4., 6.], dtype=float32)

In [15]:
tf.reduce_sum(x, axis=1).eval(session=sess)

array([3., 7.], dtype=float32)

In [16]:
tf.reduce_sum(x, axis=-1).eval(session=sess)

array([3., 7.], dtype=float32)

In [18]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval(session=sess)

5.0