In [17]:
import tensorflow as tf

In [18]:
import numpy as np

In [19]:
import pprint as pp

In [20]:
sess = tf.Session()

In [21]:
t0 = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10 ,11]]])

In [22]:
pp.pprint(t)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [23]:
t.shape

(2, 2, 3)

In [26]:
t1 = tf.reshape(t, shape=[-1, 3]).eval(session=sess)

In [27]:
pp.pprint(t1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])


In [28]:
t1.shape

(4, 3)

In [29]:
t2 = tf.reshape(t, shape=[-1, 1, 3]).eval(session=sess)

In [30]:
pp.pprint(t2)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])


In [31]:
t2.shape

(4, 1, 3)

In [38]:
t3 = tf.reshape(t, shape=[2, 1, 1, -1]).eval(session=sess)

In [39]:
pp.pprint(t3)

array([[[[ 0,  1,  2,  3,  4,  5]]],


       [[[ 6,  7,  8,  9, 10, 11]]]])


In [40]:
t3.shape

(2, 1, 1, 6)

In [41]:
t4 = tf.squeeze([[0], [1], [2]]).eval(session=sess)

In [42]:
pp.pprint(t4)

array([0, 1, 2])


In [43]:
t5 = tf.expand_dims([0, 1, 2], 1).eval(session=sess)

In [44]:
pp.pprint(t5)

array([[0],
       [1],
       [2]])
