In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)

In [4]:
x_data = xy[:,0:-1]

In [5]:
print(x_data[0:3])

[[1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 4. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 4. 1. 0. 1.]
 [0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0.]]


In [6]:
y_data = xy[:,[-1]]

In [7]:
print(y_data[0:3])

[[0.]
 [0.]
 [3.]]


In [8]:
nb_classes = 7

In [9]:
X = tf.placeholder(shape=x_data.shape, dtype=tf.float32, name='X')

In [10]:
Y = tf.placeholder(shape=y_data.shape, dtype=tf.int32, name='Y')

In [11]:
Y_one_hot = tf.one_hot(Y, nb_classes)

In [12]:
Y_one_hot = tf.reshape(Y_one_hot, shape=[-1, nb_classes])

In [13]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(Y_one_hot, feed_dict={Y:y_data})[0:3])

[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [14]:
W = tf.Variable(tf.random_normal(shape=[x_data.shape[-1], nb_classes]), dtype=tf.float32, name='weight')

In [15]:
b = tf.Variable(tf.random_normal(shape=[nb_classes]), dtype=tf.float32, name='bias')

In [16]:
logits = tf.matmul(X, W) + b

In [17]:
hypothesis = tf.sigmoid(logits)

In [18]:
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y_one_hot)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [19]:
cost = tf.reduce_mean(cost_i)

In [20]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [21]:
prediction = tf.argmax(hypothesis, 1)

In [22]:
correct_prediction = tf.equal(prediction,  tf.argmax(Y_one_hot, 1))

In [23]:
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [24]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2000):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict={X: x_data, Y: y_data})
            print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(step, loss, acc))
    # Let's see if we can predict
    pred = sess.run(prediction, feed_dict={X: x_data})
    # y_data: (N,1) = flatten => (N, ) matches pred.shape
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

Step:     0	Loss: 6.315	Acc: 3.96%
Step:   100	Loss: 1.857	Acc: 46.53%
Step:   200	Loss: 1.382	Acc: 58.42%
Step:   300	Loss: 1.149	Acc: 62.38%
Step:   400	Loss: 0.995	Acc: 71.29%
Step:   500	Loss: 0.891	Acc: 72.28%
Step:   600	Loss: 0.817	Acc: 73.27%
Step:   700	Loss: 0.760	Acc: 78.22%
Step:   800	Loss: 0.715	Acc: 80.20%
Step:   900	Loss: 0.678	Acc: 81.19%
Step:  1000	Loss: 0.646	Acc: 82.18%
Step:  1100	Loss: 0.618	Acc: 82.18%
Step:  1200	Loss: 0.593	Acc: 82.18%
Step:  1300	Loss: 0.570	Acc: 82.18%
Step:  1400	Loss: 0.550	Acc: 86.14%
Step:  1500	Loss: 0.531	Acc: 86.14%
Step:  1600	Loss: 0.514	Acc: 86.14%
Step:  1700	Loss: 0.498	Acc: 86.14%
Step:  1800	Loss: 0.483	Acc: 86.14%
Step:  1900	Loss: 0.469	Acc: 86.14%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[T