In [19]:
import tensorflow as tf

In [20]:
import numpy as np

In [21]:
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-5)

In [22]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
 [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
 [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
 [816, 820.958984, 1008100, 815.48999, 819.23999],
 [819.359985, 823, 1188100, 818.469971, 818.97998],
 [819, 823, 1198100, 816, 820.450012],
 [811.700012, 815.25, 1098100, 809.780029, 813.669983],
 [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [23]:
print(xy[0:3])

[[8.28659973e+02 8.33450012e+02 9.08100000e+05 8.28349976e+02
  8.31659973e+02]
 [8.23020020e+02 8.28070007e+02 1.82810000e+06 8.21655029e+02
  8.28070007e+02]
 [8.19929993e+02 8.24400024e+02 1.43810000e+06 8.18979980e+02
  8.24159973e+02]]


In [24]:
xy = MinMaxScaler(xy)

In [25]:
print(xy[0:3])

[[0.99999948 0.99999945 0.         0.99999958 0.99999955]
 [0.70548455 0.70439514 1.         0.71881752 0.83755754]
 [0.54412521 0.50274796 0.57608696 0.60646775 0.6606328 ]]


In [26]:
x_data = xy[:, 0:-1]

In [27]:
print(x_data[0:3])

[[0.99999948 0.99999945 0.         0.99999958]
 [0.70548455 0.70439514 1.         0.71881752]
 [0.54412521 0.50274796 0.57608696 0.60646775]]


In [28]:
y_data = xy[:, [-1]]

In [29]:
print(y_data[0:3])

[[0.99999955]
 [0.83755754]
 [0.6606328 ]]


In [30]:
X = tf.placeholder(shape=[None, 4], dtype=tf.float32, name='X')

In [31]:
Y = tf.placeholder(shape=[None, 1], dtype=tf.float32, name='Y')

In [32]:
W = tf.Variable(tf.random_normal(shape=[4,1]), shape=[4,1], dtype=tf.float32, name='weight')

In [33]:
b = tf.Variable(tf.random_normal(shape=[1]), shape=[1], dtype=tf.float32, name='bias')

In [34]:
hypothesis = tf.matmul(X, W) + b

In [35]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [36]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [37]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, W_val, b_val, predicted_Y, observed_Y, _ = sess.run([cost, W, b, hypothesis, Y, optimizer], feed_dict={X: x_data, Y:y_data})
        if step%100 == 0:
            print(step, cost_val, W_val, b_val, predicted_Y, observed_Y)

0 0.6302396 [[-1.1753926 ]
 [ 0.8572345 ]
 [-1.028617  ]
 [ 0.38757414]] [0.2404213] [[ 0.27308398]
 [-0.7718521 ]
 [-0.35591894]
 [ 0.15464333]
 [-0.11279432]
 [-0.14115779]
 [-0.03850563]
 [-0.2585193 ]] [[0.9999995 ]
 [0.83755755]
 [0.6606328 ]
 [0.438009  ]
 [0.4262438 ]
 [0.49276114]
 [0.1859723 ]
 [0.        ]]
100 0.07680984 [[-0.9664824]
 [ 1.0617763]
 [-0.765728 ]
 [ 0.5981712]] [0.5065987] [[1.1995163 ]
 [0.23538682]
 [0.43534172]
 [0.7039394 ]
 [0.57809377]
 [0.5259057 ]
 [0.3696831 ]
 [0.18077752]] [[0.9999995 ]
 [0.83755755]
 [0.6606328 ]
 [0.438009  ]
 [0.4262438 ]
 [0.49276114]
 [0.1859723 ]
 [0.        ]]
200 0.058806658 [[-0.9442058]
 [ 1.088799 ]
 [-0.6539705]
 [ 0.6106705]] [0.44379747] [[1.1992327 ]
 [0.32889947]
 [0.47083297]
 [0.6754622 ]
 [0.58011186]
 [0.52740455]
 [0.33554572]
 [0.17991847]] [[0.9999995 ]
 [0.83755755]
 [0.6606328 ]
 [0.438009  ]
 [0.4262438 ]
 [0.49276114]
 [0.1859723 ]
 [0.        ]]
300 0.04550016 [[-0.9285619]
 [ 1.1079571]
 [-0.559003 ]
 [