In [1]:
import tensorflow as tf

In [2]:
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]

In [3]:
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

In [4]:
# Evaluation our model using this test dataset

In [5]:
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]

In [6]:
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

In [7]:
X = tf.placeholder(shape=[None, 3], dtype=tf.float32, name='X')

In [8]:
Y = tf.placeholder(shape=[None, 3], dtype=tf.float32, name='Y')

In [9]:
W = tf.Variable(tf.random_normal(shape=[3, 3]), shape=[3, 3], dtype=tf.float32, name='weight')

In [10]:
b = tf.Variable(tf.random_normal(shape=[3]), shape=[3], dtype=tf.float32, name='bias')

In [11]:
logits = tf.matmul(X, W) + b

In [12]:
hypothesis = tf.nn.softmax(logits)

In [13]:
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [14]:
cost = tf.reduce_mean(cost_i)

In [15]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [16]:
predicted_Y = tf.argmax(hypothesis, 1)

In [17]:
is_correct = tf.equal(predicted_Y, tf.argmax(Y, 1))

In [18]:
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [19]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, W_val, b_val, _ = sess.run([cost, W, b, optimizer], feed_dict={X: x_data, Y: y_data})
        if step%200 == 0:
            print(step, cost_val, W_val)
    # prediction
    print ("Prediction:", sess.run(predicted_Y, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy:", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 7.0310216 [[-0.7675113  -0.31913346 -1.8201921 ]
 [ 1.0411447   0.46438655  0.36895606]
 [-1.0083581   1.6787282  -0.02556519]]
200 1.2136252 [[-0.82974786 -0.65098864 -1.4261001 ]
 [ 1.3050084  -0.10778996  0.6772693 ]
 [-0.26538256  0.7557547   0.15443279]]
400 1.004327 [[-0.95320785 -0.81039536 -1.1432327 ]
 [ 1.1155854   0.10276482  0.65613717]
 [-0.01564449  0.6088484   0.0516014 ]]
600 0.86776286 [[-1.0578277  -0.94338644 -0.905621  ]
 [ 0.97501796  0.2639306   0.6355392 ]
 [ 0.175615    0.5044869  -0.03529628]]
800 0.7815081 [[-1.1535908  -1.0480868  -0.70515674]
 [ 0.88035053  0.37478796  0.6193488 ]
 [ 0.31477955  0.44047523 -0.11044926]]
1000 0.7253648 [[-1.2451229  -1.1279244  -0.5337866 ]
 [ 0.8228984   0.445635    0.60595375]
 [ 0.41273943  0.40669218 -0.17462593]]
1200 0.6859764 [[-1.3337058  -1.1881808  -0.38494733]
 [ 0.7910588   0.4899899   0.59343874]
 [ 0.48240724  0.39132166 -0.2289231 ]]
1400 0.65617657 [[-1.4194472  -1.2337325  -0.25365517]
 [ 0.774866    0.5184