In [111]:
import tensorflow as tf

In [112]:
import numpy as np

In [113]:
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)

In [114]:
x_data = xy[:, 0:-1]

In [115]:
print(x_data[0:5])

[[1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 4. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 4. 1. 0. 1.]
 [0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 4. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 4. 1. 0. 1.]]


In [116]:
y_data = xy[:, [-1]]

In [117]:
X = tf.Variable(x_data, dtype=tf.float32)

In [118]:
Y = tf.Variable(y_data, dtype=tf.int32)

In [119]:
nb_classes = 7

In [120]:
Y_one_hot = tf.one_hot(Y,nb_classes)

In [139]:
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])

In [140]:
class Model(object):
    def __init__(self, inputs, outputs):
        self.W = tf.Variable(tf.random.normal(shape=[inputs.shape[-1],outputs.shape[-1]]), dtype=tf.float32, name='weight')
        self.b = tf.Variable(tf.random.normal(shape=[outputs.shape[-1]])  , dtype=tf.float32, name='bias')
    
    def __call__(self, X):
        return tf.nn.softmax(tf.matmul(X, self.W) + self.b)        

In [125]:
def train_step(dist_inputs):
    def step_fn(inputs):
        features, labels = inputs
        with tf.GradientTape() as tape:
            logits = model(features)
            cross_entropy = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels)
            loss = tf.reduce_sum(cross_entropy) * (1.0 / global_batch_size)
        grads = tape.gradient(loss, model.trainable_variables)
        

In [126]:
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y_one_hot)

In [127]:
cost = tf.reduce_mean(cost_i)

In [128]:
@tf.function
def train(model, inputs, outputs, learning_rate=1e-5):
    with tf.GradientTape() as t:
        current_loss = cost(model(inputs), outputs)
    dW, db = t.gradient(current_loss, [W, b])
    W.assign_sub(learning_rate * dW)
    b.assign_sub(learning_rate * db)

In [129]:
learning_rate = 0.1

In [138]:
for step in range(2001):
    current_W = W
    current_b = b
    with tf.GradientTape() as t:
        current_loss = cost
    print(current_loss)
    dW, db = t.gradient(current_loss, [W, b])
   
    W.assign_sub(learning_rate * dW)
    b.assign_sub(learning_rate * db)
    print(hypothesis)
    expected_y = tf.math.argmax(hypothesis, 1)
    
    if step%100 == 0:
        print(step, expected_y)
    
    

tf.Tensor(1.9459102, shape=(), dtype=float32)


TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'