In [2]:
import tensorflow as tf

In [3]:
x_data = tf.Variable([[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]], shape=(8,4), dtype=tf.float32)

In [4]:
y_data = tf.Variable([[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]], shape=(8,3), dtype=tf.float32)

In [5]:
class Model(object):
    def __init__(self):
        self.W = tf.Variable(tf.random.normal(shape=[4,3]), dtype=tf.float32, name='weight')
        self.b = tf.Variable(tf.random.normal(shape=[3])  , dtype=tf.float32, name='bias')
    
    def __call__(self, X):
        return tf.nn.softmax(tf.matmul(X, self.W) + self.b)

In [6]:
@tf.function
def loss (expected_y, observed_y):
    return -tf.reduce_mean(tf.reduce_sum(observed_y * tf.math.log(expected_y), axis=1))

In [7]:
@tf.function
def train(model, inputs, outputs, learning_rate=1e-5):
    with tf.GradientTape() as t:
        current_loss = loss(model(inputs), outputs)
    dW, db = t.gradient(current_loss, [model.W, model.b])
    model.W.assign_sub(learning_rate * dW)
    model.b.assign_sub(learning_rate * db)

In [8]:
model = Model()

In [14]:
for step in range(2001):
    current_W = model.W
    current_b = model.b
    current_loss = loss(model(x_data), y_data)
    train(model, x_data, y_data, 0.05)
    print(tf.math.argmax(model(x_data), 1))
    expected_y = tf.cast(model(x_data) > 0.5, dtype=tf.float32)
    #accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, y_data), dtype=tf.float32))
    if step%100 == 0:
        pass
        #print(step, expected_y.numpy(), y_data.numpy())
        #print(step, accuracy.numpy())
        #print(step, predicted.numpy(), model(x_data).numpy(), y_data.numpy(), accuracy.numpy())

tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0],